### ISSUE TITLE
closure problem

### ISSUE THREAD

**Issue by dlinnemeyer** [bobthecow/psysh#106]
Trying some pretty strange code playing with closures and ran into this error:

```
PHP warning:  Cannot bind an instance to a static closure on /data/home/dlinnemeyer/nematode/teaching-meetings/overloading/overload.phpon line 12
```

I'm including the following file in psysh, which triggers the error:

```
<?php

$callable = function(){ echo $this->foo . "/n"; };

class Test {
    public $foo;
}

$test = new Test();
$test->foo = "bar";

$bound_callable = $callable->bindTo($test);

$bound_callable();
```

Also, I get these error messages on exit from psysh:

```
PHP Warning:  unserialize(): Function spl_autoload_call() hasn't defined the class it was called for in /data/home/dlinnemeyer/psysh/src/Psy/ExecutionLoop/ForkingLoop.php on line 64
PHP Stack trace:
PHP   1. {main}() /data/home/dlinnemeyer/psysh/bin/psysh:0
PHP   2. call_user_func() /data/home/dlinnemeyer/psysh/bin/psysh:100
PHP   3. {closure:/data/home/dlinnemeyer/psysh/bin/psysh:40-100}() /data/home/dlinnemeyer/psysh/bin/psysh:100
PHP   4. Psy\Shell->run() /data/home/dlinnemeyer/psysh/bin/psysh:99
PHP   5. Symfony\Component\Console\Application->run() /data/home/dlinnemeyer/psysh/src/Psy/Shell.php:215
PHP   6. Psy\Shell->doRun() /data/home/dlinnemeyer/psysh/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   7. Psy\ExecutionLoop\ForkingLoop->run() /data/home/dlinnemeyer/psysh/src/Psy/Shell.php:243
PHP   8. unserialize() /data/home/dlinnemeyer/psysh/src/Psy/ExecutionLoop/ForkingLoop.php:64
```

The example works fine when run through php itself.

**Comment by bobthecow** [comment]
I think I figured out what's happening. I'm just not sure how to work around it :)

Every bit of code you run in PsySH is executed inside a closure. This includes any files you include or require. See, for example, [this line](https://github.com/bobthecow/psysh/blob/master/src/Psy/ExecutionLoop/Loop.php#L45), where the files passed in from the command line are included (e.g. `psysh test.php`).

If you define a closure inside a closure defined inside a class (or inside a file included by a closure defined inside a class), it will inherit the scope of the outer closure. That means that `$this` will be defined inside the inside closure, and it'll refer to the class the outside closure was defined inside. It's a little weird and unexpected to have a value for `$this` inside the file you included in PsySH, so the shell explicitly unbinds it's execution closure from itself, which kills the `$this` (unless it has another `$this` value from where you started the shell… in that case it'll bind to the other `$this` instead). See [this block](https://github.com/bobthecow/psysh/blob/master/src/Psy/ExecutionLoop/Loop.php#L106-L110).

Unfortunately PHP's closures don't deal well with switching bindings. Unbinding the `$this` still leaves us in the scope of the class where the closure was defined, but now we're in 'static' instead of object scope. And that's a crappy place to be, because PHP doesn't let you get back out of static scope, even if you want to. Here's the relevant [snippet from the docs](http://php.net/manual/en/closure.bindto.php):

> This function will ensure that for a non-static closure, having a bound instance will imply being scoped and vice-versa. To this end, non-static closures that are given a scope but a NULL instance are made static and non-static non-scoped closures that are given a non-null instance are scoped to an unspecified class.

If a closure ever has static scope, it can never be re-bound in an object scope. If it ever has object _or_ static scope, it can never be re-bound with no class scope… at least as far as I can tell.

So when PsySH defines the loop execution closure, it gets object scope. It then unbinds the closure so that `$this` will go away, and it becomes static scope instead. This static scope then infects all closures defined inside the REPL, and all closures defined in files included into the REPL, and there's no way to re-bind them to object scope _or_ no-scope.

Sounds pretty bleak, huh? Yay PHP!

I started out this novel of a comment explaining what I thought was the problem, and why PHP acted that way, and how there wasn't any way to work around it, but in the process of fact checking my assumptions, I just came up with a (super-ghetto) way to work around it!

I'll push that to a feature branch in a second :)
