### ISSUE TITLE
Replace Presenter system by VarDumper

### ISSUE THREAD

**Issue by nicolas-grekas** [bobthecow/psysh#180]
Hi,

I'm not sure if you know about symfony/var-dumper, so basically it's a rock solid variable presenter (using your "presenter" vocabulary).
Documentation and examples are avail. in the doc:
http://symfony.com/doc/current/components/var_dumper/index.html

I wonder if you might be interested in replacing your Presenter module by VarDumper?

**Comment by bobthecow** [comment]
I do know about VarDumper, and it's a great library for what it's intended, but it's not the best fit for a REPL for a couple of reasons. First, it requires PHP >= 5.5.9, which would cut off a large number of our users. Second, it's a good general purpose tool intended to replace `var_dump()` or `serialize()`, while Presenters in PsySH are intended as an opinionated, extensible, specialized tool for viewing relevant data.

As an example, here's what an Exception looks like when it's printed as a return value in PsySH:

![exception](https://cloud.githubusercontent.com/assets/53660/6644039/3fdfd772-c96e-11e4-8826-2a8a2b2eea26.png)

Here's what it looks like when you use the `dump` command to get a bit more info:

![dump-exception](https://cloud.githubusercontent.com/assets/53660/6644043/4c7d97c6-c96e-11e4-8ac6-8ef20c01f1d1.png)

You'll notice that this triggered output paging, so there's quite a bit of info there. If we just care about some high level things, we can use `--depth` to limit the dump as well:

![dump-depth](https://cloud.githubusercontent.com/assets/53660/6644062/7a6b6f00-c96e-11e4-85d7-f37ef8b15519.png)

Now compare that to VarDumper output:

![var-dumper](https://cloud.githubusercontent.com/assets/53660/6644065/81b827a8-c96e-11e4-8a20-18dd04809386.png)

… and:

![var-dumper-2](https://cloud.githubusercontent.com/assets/53660/6644070/8837f40a-c96e-11e4-8db8-fd76d044b2fc.png)

… and:

![var-dumper-3](https://cloud.githubusercontent.com/assets/53660/6644074/8e493c3c-c96e-11e4-9ec0-8d80f8fc6303.png)

… and:

![var-dumper-4](https://cloud.githubusercontent.com/assets/53660/6644079/936fe38c-c96e-11e4-87fb-ff4f46bc73eb.png)

… and I got bored screenshotting things after I made it about 1/10th of the way through the output :)

Just think of how awful that would be if the return value from your line of code was an exception? Now all your code, all your context, the return values of your last few commands, and everything you've typed is thousands of lines back in your window scroll buffer. Depending on your terminal settings, it might be gone forever. And it would do that *every time you touch an exception*. 

Sure, that could be fixed by buffering the output from the dumper and sending it through the output pager. Sure it could be fixed by registering custom cloners in VarDumper that limit output to something more sane. But there's no way of registering variable depth dumpers. There's no way of dumping only public properties by default, and dumping protected and private properties with another command. It's not as usable by default, nor as flexible as the approach PsySH currently uses.

Presenters try to show you the exact right amount of data the first time (i.e. the implicit return value print).  They try to show you all the data, but in a manageable manner, when you use the `dump` command.

That's why there are [explicit presenters for more than just generic objects and arrays](https://github.com/bobthecow/psysh/tree/master/src/Psy/Presenter). That's why [frameworks often ship their own presenters, for their own specific needs](https://github.com/laravel/framework/tree/5.0/src/Illuminate/Foundation/Console/Tinker/Presenters). And that's why we're working on a plugin architecture, to make it super easy to register presenters for anything you want.

That said, when you need more info than the implicit return value printing or the `dump` command will give you, you should use `dump()` yourself. It's still better at what it's made for :)

**Comment by nicolas-grekas** [comment]
You may have been mislead by the master branch, which requires 5.5.9: VarDumper requires 5.3.3 in the current stable release.

You maybe didn't notice also that VarDumper exposes an extensive API to deal with dumps. With it, you can hook it how exactly each type/class should be dumped. The mechanism is called Caster and there are already a bunch of them. See the short intro in the doc here: http://symfony.com/doc/current/components/var_dumper/advanced.html#casters

It would be very easy to have two different set of casters, one used for the short excerpt you need on the rePl, and an other one for the "dump" command. Framework could continue to provide specific casters for their objects very easilly.

VarDumper has unprecedented handling of references for example. It bet you want it.
See examples and try with PsySH :)
http://symfony.com/doc/current/components/var_dumper/introduction.html#dump-examples-and-output

I can help of course.

**Comment by bobthecow** [comment]
Oh, I didn't notice that I was looking at master branch, thanks for pointing that out. I do know about the VarDumper API. I do know about Casters :)

My point remains: the purpose and implementation of VarDumper is just plain wrong for a REPL. Look at those screenshots again. You don't want all of that information. You want a very limited, opinionated subset of information. So we could switch to VarDumper instead of PresenterManager, but we'd still have to reimplement all the existing Presenters in terms of VarDumper — essentially writing our own opinionated Casters. Twice (once for the REPL return value, once for `dump`) … which would lose any of the benefit of using existing Casters.

Yes, I do plan to fix references. That's one thing from VarDumper that PsySH is really lacking. But that doesn't warrant switching, it warrants fixing references in PresenterManager ;)

**Comment by nicolas-grekas** [comment]
It may, because handing references, especially hard ones, is hard to my experience. It may not only be a fix. Whereas the Casters you'd need should be a few lines long.
I may try for you :-) Thanks for your time and answers!

**Comment by bobthecow** [comment]
Done. Thanks @nicolas-grekas :)
