### ISSUE TITLE
json_last_error()

### ISSUE THREAD

**Issue by Server4001** [bobthecow/psysh#192]
php -a
$str = "{'Organization': 'PHP Documentation Team'}";
$arr  = json_decode($str, true); // null
json_last_error(); // int(4)

psysh:
$str = "{'Organization': 'PHP Documentation Team'}";
$arr = json_decode($str, true); // null
json_last_error(); // int(0)

**Comment by bobthecow** [comment]
Yeaaaah. That's a thing that happens. Unfortunately, due to the nature of PHP's json encoding error handling, I don't actually know how to stop it from happening. Short of writing our own JSON encoder, I guess.

We use JSON encoding when rendering return values which include array keys, function signatures and scalars. In writing the return value from `json_decode`, we're calling `json_encode` (successfully) which overwrites the error returned by `json_last_error` with `JSON_ERROR_NONE`.

You can work around it by doing something like this:

```php
$arr = json_decode($str, true); $err = json_last_error();
```

… which ensures that the "last error" is captured before it has a chance to be overwritten.

**Comment by Server4001** [comment]
Ah. Thanks for the quick response and the work around!

**Comment by bobthecow** [comment]
No problem!
