### ISSUE TITLE
MSYS2 issue while using psysh

### ISSUE THREAD

**Issue by freijbe** [bobthecow/psysh#201]
Hi everyone,

While i'm typing code on Psysh with MSYS2 , psysh shuts down with no reason at all. I just get this message : >>> Exit:  Ctrl+D.
I have to precise that i don't use CTRL + D shortcut, even distractedly.

It also happens when i'm not typing for about 30seconds.

When i'm trying to use the CTRL+D shortcut, nothing happens in psyshell, so I think it's not my terminal.

**Comment by bobthecow** [comment]
Ooh, that sounds like the exact opposite of how you want Ctrl+D to work :-/

Unfortunately I have no experience with Windows or MSYS2 or anything of the sort, so I don't have any particular insight into fixing this. I'd start with disabling readline, and seeing if that helps. Add this to `~/.config/psysh/config.php` (or maybe `C:\Users\{USER}\AppData\Roaming\PsySH\config.php`, since you're on Windows?):

```php
return [
  'useReadline' => false,
];
```

**Comment by freijbe** [comment]
Hello bobthecow,

I tried it and unfortunately it doesn't work. Still get this message  >>> Exit: Ctrl+D and when i use this shortcut nothing happens.

**Comment by agkozak** [comment]
A good workaround when using MSYS2 is to launch `psysh` using `winpty`, e.g.

`winpty ~/AppData/Roaming/Composer/vendor/bin/psysh.bat`

**Comment by squarefractal** [comment]
@freijbe 

> It also happens when i'm not typing for about 30seconds.

This is be due to PHP's `max_execution_time`; increasing it should work.

(Yes, although max_execution_time doesn't make sense for the CLI SAPI, it is apparently used on Windows.)

**Comment by bobthecow** [comment]
I've added a section to the [Troubleshooting](https://github.com/bobthecow/psysh/wiki/Troubleshooting) page about this!
