### ISSUE TITLE
0.5 Release

### ISSUE THREAD

**Issue by GrahamCampbell** [bobthecow/psysh#210]
Is there anything I can do to help speed this along?

**Comment by GrahamCampbell** [comment]
Ping @bobthecow. :)

**Comment by bobthecow** [comment]
Sorry, life and work has been crazy the past few weeks. I'll get on this :)

**Comment by GrahamCampbell** [comment]
Awesome. :)

**Comment by bobthecow** [comment]
I'd wanted to work through some of the pull requests — possibly fleshing out the plugin manager idea a bit and moving some of them to plugins — but I'm leaning toward just shipping what we have as v0.5.0, since it's stable and works and has a decent amount of changes already. Thoughts?

Sorry, @Markcial, I know you've been waiting on me for a while :(

**Comment by Markcial** [comment]
don't worry i was busy too, whatever you need ping me back. :D

**Comment by bobthecow** [comment]
Done: https://github.com/bobthecow/psysh/releases/tag/v0.5.0

**Comment by GrahamCampbell** [comment]
Great. I'll get that laravel PR sorted out then.

**Comment by bobthecow** [comment]
:+1:

**Comment by GrahamCampbell** [comment]
@bobthecow Your php parser change is broken and needs reverting asap please. It prevents installs on Laravel 5.1 as it prevents us using 1.3.

`^1.2.1` allows all 1.x equal to or greater than 1.2.1, but you changed it to use `~1.2.1` which doesn't allow installs on 1.3. :(

**Comment by bobthecow** [comment]
Crap, you're right. I got my twiddles and my hats mixed up :(

**Comment by GrahamCampbell** [comment]
https://github.com/bobthecow/psysh/pull/213
