### ISSUE TITLE
Execution order inconsistent and incorrect

### ISSUE THREAD

**Issue by Rican7** [bobthecow/psysh#212]
I was toying with some boolean operation orders and noticed that logical short-circuiting was working correctly with a non-existent method, but not with a non-existent function.

Example:

![screen shot 2015-07-02 at 6 18 01 pm](https://cloud.githubusercontent.com/assets/742384/8489173/b5a7413c-20e6-11e5-925c-2ddf9efec4c7.png)

The expectation is that this code should dump 4 `bool(true)` lines:

```php
$dt = new DateTime();

var_dump(true || $dt->nonExistentMethod());
var_dump(true || non_existent_func());

var_dump(eval('return (true || $dt->nonExistentMethod());'));
var_dump(eval('return (true || non_existent_func());'));
```

3v4l example: http://3v4l.org/mOdJk

**Comment by Rican7** [comment]
Not sure, but this miiiiight have something to do with #193.

**Comment by bobthecow** [comment]
It's because PsySH is detecting fatal errors and stopping them before they happen. In this case, your code is also stopping them before they happen, but there's no way PsySH can know that without solving the halting problem :(

The ultimate answer is to wait until PHP ships better fatal error handling (should be in 7.0?) and we can remove some of those checks (at least for non-windows users). Until then, we have to choose between protecting you from yourself, and occasionally hitting input that *should* be valid but which looks a lot like it's invalid.

**Comment by Rican7** [comment]
Ahh, I see, that's interesting. I understand, yea, because otherwise it would fatally error and the shell session would halt completely, correct?

If that's the case, then feel free to close this as invalid. And thank you for the explanation. 👍

**Comment by bobthecow** [comment]
I'll give it both a "wontfix" and "someday" :)

**Comment by Rican7** [comment]
Haha. Sounds good. Thanks man. 👍
