### ISSUE TITLE
Unable to allow notices to be acceptible (and ignore their output)

### ISSUE THREAD

**Issue by ramondelafuente** [bobthecow/psysh#220]
Using PsySH for Lambdalicious I'd like to allow notices to pass without any output. It seems this is not currently possible?

**Comment by bobthecow** [comment]
You should be able to ignore them by changing your `error_reporting` level. See http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

**Comment by ramondelafuente** [comment]
I might be mis-interpreting something, but the Shell() class has a `getSeverity()` method that returns warning or error - but it's never suppressed.

Also, the ShellTest has a `testHandlingErrors` method that sets error_reporting to `& ~E_USER_NOTICE` and asserts this:

```
$this->assertContains('PHP error:', $streamContents);
$this->assertContains('wheee',      $streamContents);
$this->assertContains('line 13',    $streamContents);
```
while the `testNotHandlingErrors` throws an Exception.

That led me to believe that it's not possible to _suppress_ the output of E_USER_NOTICE.

**Comment by bobthecow** [comment]
It's suppressing the error itself, but it is telling you about it :)

I think the confusion arises because PsySH respects `error_reporting`, but logs all warnings and errors regardless of the current level.

Check out the dev branch. I've added an additional `errorLoggingLevel` configuration option, which allows overriding this default. If you set it to `0`, all `error_reporting` level errors will still be thrown, but no additional errors will be logged.

You can also set it to any valid `error_reporting` values, e.g. `E_ALL & ~E_NOTICE`, which should do the trick for you.

**Comment by ramondelafuente** [comment]
It does. :+1: (and some more :+1:  :+1:  :+1:  for writing the whole thing within hours of the issue)

**Comment by bobthecow** [comment]
No problem at all.
