### ISSUE TITLE
PHP7 anonymous class support

### ISSUE THREAD

**Issue by mpyw** [bobthecow/psysh#229]
#### Summary

Dumping of an anonymous class object causes a catchable fatal error.

##### Code:

```php
$obj = new class() {};
```

##### Error:

```text
PHP Catchable fatal error:  Object of class PhpParser\Node\Stmt\Class_ could not be converted to string in /Users/mpyw/.composer/vendor/psy/psysh/src/Psy/CodeCleaner/NamespaceAwarePass.php on line 69
```

**Comment by mpyw** [comment]
Oops, should I report not here but [nikic/PHP-Parser](https://github.com/nikic/PHP-Parser)?

**Comment by bobthecow** [comment]
That one is likely broken on the PsySH end, to be honest.

The parse tree changes for anonymous classes (as you might expect) but there's a good chance that our code is making assumptions about it that no longer hold. If I had to guess, it's because anonymous classes don't have names, and somewhere we're trying to save the names of the classes we know about :)

Thanks for reporting. I'll take a look into it.

**Comment by bobthecow** [comment]
This is fixed in `develop` and will go out in the next release. Thanks for the bug report!

**Comment by mpyw** [comment]
thx :+1:
