### ISSUE TITLE
Automatically require /vendor/autoload.php if in project root

### ISSUE THREAD

**Issue by elnoro** [bobthecow/psysh#262]
Hello. 
Shouldn't psysh automatically use current project's autoload.php when run in project root?
This would be useful for playing around with project and its dependencies without hijacking into existing code. 
Of course, users can do it manually by typing `require` statement directly after running Psysh.
Still, could be an improvement for psysh's usability.

Thanks for an awesome product, btw.

**Comment by bobthecow** [comment]
If you add psysh to your project's (dev) dependencies, it will :)

**Comment by elnoro** [comment]
Thanks. Took a look into documentation before posting this, still missed somehow.

**Comment by bobthecow** [comment]
No worries, it's not in the documentation.

It's actually a side effect of a change that shipped a few versions ago where a globally installed psysh tries to defer to the current composer project's required version if one exists. And it does that by using the local composer autoloader rather than the globally installed one.
