### ISSUE TITLE
Treatments of strings those contain backslashes

### ISSUE THREAD

**Issue by mpyw** [bobthecow/psysh#282]
![2016-02-14 0 34 33](https://cloud.githubusercontent.com/assets/1351893/13028458/eda727a4-d2b2-11e5-9c63-c6fe7383ebff.png)
:tired_face:

**Comment by bobthecow** [comment]
Unfortunately, this is impossible to represent using Symfony's OutputFormatter, due to a bug/limitation in their escaping logic. Here, [PsySH escapes and wraps the string](https://github.com/bobthecow/psysh/blob/master/src/Psy/VarDumper/Dumper.php#L59):

```php
$value = "<{$style}>" . $this->formatter->escape($value) . "</{$style}>";
```

… which in your case would return `<string>\</string>`, the OutputFormatter code to spit out a green string.

_But_, it turns out [OutputFormatter escapes literal `<` characters by adding a `\` in front of them](https://github.com/symfony/console/blob/master/Formatter/OutputFormatter.php#L34-L37):

```php
public static function escape($text)
{
    return preg_replace('/([^\\\\]?)</', '$1\\<', $text);
}
```

… so your output is something more like `<string>&lt;/string>`. _Which wouldn't really be a problem_ except that OutputFormatter doesn't have a way of escaping that `\` to prevent it from escaping the `<` 😕

Trying to escape it ourselves just results in more `\` in front of the `</string>`:

<img width="762" alt="screen shot 2016-02-14 at 11 02 22 am" src="https://cloud.githubusercontent.com/assets/53660/13035677/76647f2c-d30a-11e5-821f-e19dd3d91a21.png">

This is a long way of saying we need to take the issue up with Symfony, but unfortunately it's probably not possible to solve given their naive string representation.

**Comment by mpyw** [comment]
Omg, that's too bad :sob: 
Thank you anyway :laughing:

**Comment by bobthecow** [comment]
@mpyw I've got something that works. See symfony/symfony#17908 :smile:

**Comment by mpyw** [comment]
@bobthecow :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:
