### ISSUE TITLE
Shift to secure Urls

### ISSUE THREAD

**Issue by captn3m0** [bobthecow/psysh#290]
The current installation method:

```bash
~ $ wget psysh.org/psysh
~ $ chmod +x psysh
~ $ ./psysh
```

is insecure, because it downloads it over HTTP. If we cannot move to HTTPS, I'd recommend the following:

- Pointing the wget to a download link in the releases section on GitHub instead and upload the latest binaries there.
- Point it to a shortlink like `https://goo.gl/voeyqZ`, which expands to https://github.com/bobthecow/psysh/raw/gh-pages/psysh, thus downloading psysh from the exact same source, but over a secure medium.

**Comment by bobthecow** [comment]
I've been meaning to sort this out for a while. Unfortunately, it's not possible to use SSL with a non-github.io domain on GitHub Pages. I could use Cloudflare or similar to use SSL for psysh.org, but it'd still have an unsecure connection between Cloudflare and GitHub's servers.

The `psysh` binary should probably be hosted on the releases page anyway, so moving it there isn't a problem, but that does mean the actual download path is a moving target. We could use short links to work around that, but it'd have to be a shortlink that can be updated, because having different download instructions for every release is a pain.

Ideas?

**Comment by bobthecow** [comment]
Alright, this should do for now. The instructions have been updated to say:

```
~ $ wget https://git.io/psysh
~ $ chmod +x psysh
~ $ ./psysh
```

<img width="762" alt="screen shot 2016-03-05 at 3 48 32 pm" src="https://cloud.githubusercontent.com/assets/53660/13551308/cc551a88-e2e9-11e5-977b-c4cb67414ee0.png">

**Comment by captn3m0** [comment]
That's a nice hack for git.io! :+1:
