### ISSUE TITLE
It is printed "</string>" instead of a backslash if it is in the end of a string

### ISSUE THREAD

**Issue by basilup** [bobthecow/psysh#294]
Example:
```
>>> 'a\\' ⏎
=> "a</string>"
```

**Comment by bobthecow** [comment]
Symfony Console had a bug escaping slashes — see #282 and symfony/symfony#17914

It looks like the fix made it into releases v2.3.38, v2.7.10, v2.8.3 and v3.0.3. Update your symfony/console dependency and see if it persists?

If you installed PsySH directly, just download a fresh copy. It's fixed in the last few phar releases as well.

**Comment by basilup** [comment]
Thank you, I have updated psysh and it's alright now

**Comment by bobthecow** [comment]
Great!
