### ISSUE TITLE
No history file

### ISSUE THREAD

**Issue by theofidry** [bobthecow/psysh#301]
Is it possible to use Psysh without creating an history file (to be usable in read-only environments)?

**Comment by bobthecow** [comment]
You can specify the data directory to be under `/tmp`. Is that enough?

**Comment by theofidry** [comment]
I would expect the possibility of not having any history at all and be the default if the user has no permission on the passed dir, or fallback en `/tmp` (but is it `/tmp` on Windows?).

But otherwise that's an acceptable workaround.

**Comment by bobthecow** [comment]
it calls [`sys_get_temp_dir`](http://php.net/manual/en/function.sys-get-temp-dir.php), so it does what it should on Windows as well.

**Comment by theofidry** [comment]
If you create an history file in in `/tmp`, how do you know which session is associated to it? I mean another user should not get the same history file.

**Comment by bobthecow** [comment]
I guess it'd be up to you to guarantee that each session had a unique subfolder of `/tmp`. You could easily do this in the psysh config file, since that is just PHP, and is executed at the start of every session.

We really should add support for ephemeral history. Would detecting that the data directory doesn't have write permissions be enough, or should it be a config?

**Comment by jeteon** [comment]
It sounds like you might be looking for something like https://github.com/xrgtn/nullfs to use as the data directory.

**Comment by bobthecow** [comment]
Oh! This issue has been fixed in `develop`. If the history file can't be written, it just runs without one.
