### ISSUE TITLE
we are missing an "autoexec" in it.

### ISSUE THREAD

**Issue by sdbruder** [bobthecow/psysh#317]
a way to configure a bunch of commands to be pre-executed every time will be a great addition.

(Im thinking namespacing, use of common classes and so on).

**Comment by dland** [comment]
Yep, this would be lovely. For symfony this is really useful, because you need to instantiate a kernel and boot it, at a minimum, and then be able to refer to it in order to do stuff.

In Boris, for example, you can do the following:

    $kernel = new AppKernel('dev', true);
    $kernel->loadClassCache();
    $kernel->boot();
    $boris = new \Boris\Boris('myapp> ');
    $boris->setLocal([
        'kernel' => $kernel
    ]);
    $boris->start();

And then within the REPL you can refer to $kernel and it Just Works™

**Comment by bobthecow** [comment]
Many framework or app specific PsySH adapters already do this sort of thing. For a great example, see ezsh: https://github.com/lolautruche/ezsh/blob/master/README.md

You can also set up an include file via your psysh config or by passing it on the command line. You can also do _anything you want_ inside the config file, because it's just PHP :)

The one thing you _can't_ do is pass things to be evaluated as psysh input (rather than PHP code), which is what I believe @sdbruder is looking for here.

**Comment by dland** [comment]
Yep, that's exactly the point.

For loading common classes, `defaultIncludes` works for me.

As for having variables set up at boot time, I'm looking at `Psy\Context` ... if I understand it correctly, that's where the variables created at the prompt are stored. Hence it probably just needs a `set()` method in order to create and store a variable, and then use it in a command which would do the above "injection" of the variable.

**Comment by marcosdipaolo** [comment]
> For loading common classes, `defaultIncludes` works for me.

can you tell me please how exactly would include autoload.php automatically  when starting psysh.
I see there is a defaultIncludes attribute in a Configuration class, but i don't know where to code the option.

**Comment by bobthecow** [comment]
I think the place for this sort of feature to exist is in code, not configuration. As mentioned before, a lot of frameworks and libraries have their own bin script to set up PsySH. One of those would be a great place to add input, or even custom config to allow your own custom input. See [\Psy\bin](https://github.com/bobthecow/psysh/blob/763304cbd439d0f9414382699bf8586df034c35e/src/functions.php#L303-L416) for an example of how a script like that might look.

For breakpoint-style interaction, a wrapper function would do the trick as well. [We do it internally in \Psy\debug to add an implicit `whereami` call](https://github.com/bobthecow/psysh/blob/763304cbd439d0f9414382699bf8586df034c35e/src/functions.php#L104-L106).

Either of those approaches should work great for you 🙂
