### ISSUE TITLE
PsySH stuck on specific strings.

### ISSUE THREAD

**Issue by beyondlimits** [bobthecow/psysh#352]
One day I've been peeking to a table containing binary data. I've expected PsySH to print me a pile of random characters, but instead it became stuck throwing me "Incorrectly nested style tag found." on every next input line.

The fastest way to reproduce it is trying to dump ```"\\\n"```

```
Psy Shell v0.8.1 (PHP 7.1.0 — cli) by Justin Hilemanan
>>> 2*3
=> 6
>>> "\\\n"
Symfony\Component\Console\Exception\InvalidArgumentException with message 'Incorrectly nested style tag found.'
>>> 2*3
Symfony\Component\Console\Exception\InvalidArgumentException with message 'Incorrectly nested style tag found.'
```

**Comment by jeteon** [comment]
Thought I was the only one who'd come across this. It made me stop using `base64_decode` in the REPL when I didn't know for sure the output was printable ASCII.  I guess somewhere along the way the commands are parsed in the context of the REPL and break the interpreter? 

It would be interesting to see where this is happening. I guess it would also require me to take a peek behind the blinds to see the magic at work. There's a related issue I run into sporadically where tab completion will work on a fresh invocation and then stop later. It really bugs me since this is a pretty valuable part of the REPL for me but I don't have a POC yet.
