### ISSUE TITLE
Multiple configurations

### ISSUE THREAD

**Issue by still-dreaming-1** [bobthecow/psysh#360]
Is there any way to have different configurations for psysh for different use cases? Currently, the configuration file that is used is from `~/.config/psysh/config.php`. But I use psysh in different ways depending on how / why I'm running it. For example, if I'm just running it to play around with some code, I don't want semicolons to be required. However, if I'm using psysh to run all the code from the source file I'm currently editing, as is supported by the [Codi Vim plugin](https://github.com/metakirby5/codi.vim/blob/e2aa007c5bd0e3c42c31e0c75a3fb34381655776/autoload/codi/load.vim#L142), I want it to behave a little more like the php interpreter.

It would be nice if psysh would look in the current directory for a config file before checking the other location. That would more easily allow different configurations per project which might even be tracked in that project's source code repository. It would also be nice if you could specify the location of a config file when starting psysh so it can be configured differently for use with other tools, like Codi.

**Comment by bobthecow** [comment]
`--config` :)

**Comment by bobthecow** [comment]
Sorry, I made that comment from my phone. I meant to come back and leave a longer comment, but you closed the issue and I forgot :(

`--config` is by far the easiest. If you want something a bit more … automatic(?) you can do that, too, because your config file is PHP. I've added a few more examples covering that sort of thing [to the Config section of the PsySH website](http://psysh.org/#configure).
