### ISSUE TITLE
Red vs Yellow PHP error?

### ISSUE THREAD

**Issue by jchook** [bobthecow/psysh#369]
![image 2017-04-07 at 7 37 09 pm](https://cloud.githubusercontent.com/assets/193530/24823163/ba16562e-1bc9-11e7-8a27-c0794a1dcbab.png)

What's the difference between a yellow PHP error and a red PHP error? Shouldn't there be some other indication in the text of the error? `wtf` doesn't seem to elaborate on any distinction.

**Comment by bobthecow** [comment]
The text of the error is intentionally the same as what PHP itself would display. The color is added as a bonus to let you know the severity of the error.

Any time PsySH catches an Exception (or an error rethrown as an ErrorException) for you, it saves the exception to `$_e` so you can learn more about it:

<img width="762" alt="screen shot 2017-04-07 at 9 12 09 pm" src="https://cloud.githubusercontent.com/assets/53660/24825644/254c3348-1bd7-11e7-894e-1c5c99ee2a7d.png">

In PHP, it turns out, treating an array like an object is just a notice, but treating an object of stdClass like an array is a fatal error. ¯\\\_(ツ)\_/¯ 

_N.b. the fact that PHP throws an error for the second case and lets you deal with it is new, and way awesomer than it was before. It used to just dump you back out on the command line without warning. PsySH could kind of intercept that and save you from yourself, but it couldn't even give you a pretty red exception. It looked more like this:_

<img width="762" alt="screen shot 2017-04-07 at 9 18 35 pm" src="https://cloud.githubusercontent.com/assets/53660/24825674/124dae1a-1bd8-11e7-9a6a-2f108475d51a.png">

**Comment by bobthecow** [comment]
I guess we could change the prefix to `Fatal error` for the `E_ERROR` errors we catch, to match what older versions of PHP said when that happened. But that's inconsistent with what current PHP does, now that it handles them so they're not really "fatal".

**Comment by jchook** [comment]
I appreciate the detailed response! Makes perfect sense.

**Comment by bobthecow** [comment]
No problem!
