### ISSUE TITLE
error:  Only variables can be passed by reference

### ISSUE THREAD

**Issue by skuda** [bobthecow/psysh#423]
Hi,

I was just trying Psysh, I usually develop using Python and I miss IPython badly while trying to write PHP code.

Good work with Psysh, I think is very important to have a good REPL to try interactively functions. I found this problem trying the shell though.

```
~ $ psysh --no-color
Psy Shell v0.8.11 (PHP 7.1.9 — cli) by Justin Hileman
>>> reset( array("0.4","1.2") )
PHP Fatal error:  Only variables can be passed by reference in eval()'d code on line 1
```

Why is this happening? the same code works fine in the IDE debugger.

Miguel.

**Comment by bobthecow** [comment]
[The argument to `reset` is passed by reference](http://php.net/manual/en/function.reset.php) so it's a fatal error to call it with a literal value rather than a variable name. It's the same in PsySH or PHP in interactive mode:

![screen shot 2017-09-22 at 12 40 59 pm](https://user-images.githubusercontent.com/53660/30761538-72713f2a-9f93-11e7-911c-5466db4d89e6.png)

It does work great if you assign it to a variable first:

![screen shot 2017-09-22 at 12 42 41 pm](https://user-images.githubusercontent.com/53660/30761578-9829aebe-9f93-11e7-80d9-83495de1be14.png)

**Comment by skuda** [comment]
ahh ok, sorry, didn't know about these, I just found some code using something like this:
```
$mc     = explode(' ', microtime());
$id_arr = array( end($mc), end(explode('.', reset($mc))));
```

It works in php-fpm but fails in the interactive shell, reading the documentation about end() it should be failing while trying to use end() on the generated exploded array.

I am obviously missing something here, I'm pretty new to PHP, sorry for the noise.

Miguel.
