### ISSUE TITLE
Replace default php shell with PsysSH

### ISSUE THREAD

**Issue by torinaki** [bobthecow/psysh#462]
I would like to suggest documentation addition. Unfortunately, I didn't found any manual how to make possible to replace default php shell with PsysSH.

Documentation addition
----

To replace default PHP interactive shell with PsySH you need to put following lines into `~/.bashrc` or `~/.zshrc`:
```bash
php() {
     if [[ $@ == "-a" ]]; then
         command psysh
     else
         command php "$@"
     fi
 }
```

**Comment by voronkovich** [comment]
What's the benefit?
```
>>> strlen('psysh') < strlen('php -a')
=> true
```

**Comment by torinaki** [comment]
@voronkovich there two points:
1. Personal habit to write `php -a`. I do not like to remember multiple commands which I don't need a lot. 
2. There might be more than one developer that is using development server which might not be aware of `psysh`

**Comment by GrahamCampbell** [comment]
This will have the side effect of breaking any code that calls `php -a` though?

**Comment by bobthecow** [comment]
It's not really possible to replace the default shell with PsySH, because it's not a drop-in replacement. Additionally, this wouldn't really help with developers who aren't familiar with PsySH because they won't have it installed anyway.

The best bet for you would be to add an alias so you can keep typing `php -a` but end up in `psysh` :)

**Comment by dbalabka** [comment]
It seems that might became finally possible.
Discussion: https://externals.io/message/111073
PR: https://github.com/php/php-src/pull/5962
