### ISSUE TITLE
When stopping w/in shell_exec, I can not access the PsySh Shell

### ISSUE THREAD

**Issue by bartonhammond** [bobthecow/psysh#465]
When I add ` \Psy\Shell::debug(get_defined_vars(),$this);` in code that is executed via `$output = shell_exec($cmd);`, the code stops but the PsySh Shell is not visible.

**Comment by bobthecow** [comment]
I'm afraid this will never work, because `shell_exec` isn't interactive.

Well, it kind of is, but it buffers all stdout output so it can return it as a string. Try it with this file:

```
echo "<?php var_dump(shell_exec('psysh'));" > test.php
php test.php
```

Everything should pause. Type (carefully, because you can't see the output) `help`, press enter, then type `exit` and press enter. You should get something like this:

<img width="1114" alt="screen shot 2018-01-24 at 8 00 03 pm" src="https://user-images.githubusercontent.com/53660/35370256-783b23d4-0141-11e8-89da-75ebf41eff29.png">

Python, apparently, puts their prompt on stderr instead of stdout, so the output of the python interactive shell is still buffered until the session is finished, but the input displays:

<img width="1114" alt="screen shot 2018-01-24 at 8 01 31 pm" src="https://user-images.githubusercontent.com/53660/35370267-8e53ba6e-0141-11e8-9f4e-94ebb944fd7d.png">

Either way, it's still pretty worthless. I'd suggest not using `shell_exec` if you're looking for something interactive :)

**Comment by bartonhammond** [comment]
Replacing the shell_exec sounds good to me.  Hadn’t thought about that.
