### ISSUE TITLE
timeit is rather inaccurate?

### ISSUE THREAD

**Issue by supriyo-biswas** [bobthecow/psysh#502]
Some of my basic testing with the timeit command shows that it's rather inaccurate:

```
>>> function f() {}
>>> function custom_timeit_f() { 
...   $t = 0;
...   for ($i = 0; $i < 1000; $i++) {
...     $m = microtime(true);
...     f();
...     $t += (microtime(true) - $m); 
...   }
...   echo 'Took ', $t/1000, ' seconds';
... }
>>> custom_timeit_f()
Took 2.4080276489258E-7 seconds⏎
=> null
>>> timeit f()
=> null
Command took 0.000698 seconds to complete.
>>> timeit f()
=> null
Command took 0.000542 seconds to complete.
```

I had a cursory look over the timeit command code, and it seems to execute it in a PsySH shell context, so parsing of the command is probably taking up most of the time? If that is indeed the case, maybe the benchmarking can be done inside the shell context code just after the parsing?

**Comment by bobthecow** [comment]
You're absolutely right, thanks for raising this issue!

It looks like the parsing was a big part of it, but even bigger (for non-trivial test cases) was serializing the return value and passing it back out after execution.

I've got a fix that improves things _a ton_ by injecting instrumentation into the actual code, so it's starting the timer after parsing, and ending it before serializing the return value. It's still not exactly the same—because there's still some overhead for adding the instrumentation—but it's probably close enough now:

<img width="914" alt="screen shot 2018-06-06 at 9 50 20 pm" src="https://user-images.githubusercontent.com/53660/41078820-d1937684-69d3-11e8-904c-1baa68439ec5.png">

**Comment by bobthecow** [comment]
Contrast that with the current implementation :) 

<img width="914" alt="screen shot 2018-06-06 at 9 57 30 pm" src="https://user-images.githubusercontent.com/53660/41078978-a7542f7a-69d4-11e8-91cb-1c30f6dab572.png">

**Comment by supriyo-biswas** [comment]
Thanks!
