### ISSUE TITLE
preg_last_error() not working correctly

### ISSUE THREAD

**Issue by flip111** [bobthecow/psysh#545]
php
```php
<?php

preg_match('/(\d+/', '');
if (preg_last_error() === 1) printf("Error detected\n");
```

php output
```
» php regex.php
PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 4 in /home/flip111/regex.php on line 3
Error detected
```
psysh
```
>>> preg_match('/(\d+/', '');
PHP Warning:  preg_match(): Compilation failed: missing closing parenthesis at offset 4 in /home/flip111/.configeval()'d code on line 1
>>> if (preg_last_error() === 1) printf("Error detected\n");
>>> 
```

There are more functions in PHP that retreive the last error not just about PCRE. I only tested about the PCRE one but i'm worried about the other error functions.

**Comment by bobthecow** [comment]
PsySH is written in userland code, which means things like `preg_last_error` and `json_last_error` can be polluted by library code and not return the value you expect 🙁

Unfortunately I don't think there's a great answer here. [We use `json_encode` to print return values, among other things](https://github.com/search?utf8=✓&q=json+repo%3Abobthecow%2Fpsysh+path%3A%2Fsrc&type=Code&ref=advsearch&l=&l=), and while it would be a bit annoying, we could replace it with our own escaper. But [we use regular expressions in a ton of places](https://github.com/search?q=preg+repo%3Abobthecow%2Fpsysh+path%3A%2Fsrc&type=Code), and they're not as straightforward to replace, so that one's a bit more problematic.

The one workaround would be that _within a single input_, the result will always be correct:
<img width="762" alt="Screen Shot 2019-05-26 at 3 53 01 PM" src="https://user-images.githubusercontent.com/53660/58388065-60785480-7fce-11e9-8503-b678f5a43278.png">
