### ISSUE TITLE
security issue when scan the libarry

### ISSUE THREAD

**Issue by almi9** [bobthecow/psysh#548]
Dear

I scan the library and after that, I found that security issue

file: ProcOutputPager.php 92

_OS Command Injection_

  private function getPipe()
    {
        if (!isset($this->pipe) || !isset($this->proc)) {
            **$desc = [['pipe', 'r'], $this->stream, \fopen('php://stderr', 'w')];**
            $this->proc = \proc_open($this->cmd, $desc, $pipes);

            if (!\is_resource($this->proc)) {
                throw new \RuntimeException('Error opening output stream');
            }

            $this->pipe = $pipes[0];
        }

can anyone example for me what is the risk?
thank you

**Comment by bobthecow** [comment]
The security risk here is that PsySH might allow arbitrary code execution on your system.

Which I _guarantee_ it will do, because PsySH is a REPL, and _the whole point of a REPL is to allow arbitrary code execution on your system._

I see that you’ve also opened sebastianbergmann/phpunit#3516, carlos-meneses/laravel-mpdf#9, jmespath/jmespath.php#43 and nikic/PHP-Parser#579.

I would _highly_ recommend that you hire an expert to help you understand the security implications of these issues, assess your risk, and work out possible mitigation.
