### ISSUE TITLE
Feature request: Explicitly indicate local usage

### ISSUE THREAD

**Issue by phanan** [bobthecow/psysh#626]
Currently, Psysh detects if it's being called inside a project that uses Composer and uses the "local" version instead. While pretty useful, this feature is implicit and (appears to be) undocumented, which can be confusing for new users who see something like this:

``` bash
$ cd /usr/bin && psysh
Psy Shell v0.10.3 (PHP 7.2.28 — cli) by Justin Hileman
>>> exit
$ cd ~/projects/project-with-psysh && psysh
Psy Shell v0.9.2 (PHP 7.2.28 — cli) by Justin Hileman
New version is available (current: v0.9.12, latest: v0.10.3)
>>> 
```

IMHO it would be better if we explicitly specify the usage of a local `psysh` binary e.g.

``` bash
$ cd ~/projects/project-with-psysh && psysh
Using ./vendor/bin/psysh
Psy Shell v0.9.2 (PHP 7.2.28 — cli) by Justin Hileman
New version is available (current: v0.9.12, latest: v0.10.3)
>>> 
```

Even better if the user can choose to use the global `psysh` with an overwriting option:

``` bash
$ cd ~/projects/project-with-psysh && psysh --global
Psy Shell v0.10.3 (PHP 7.2.28 — cli) by Justin Hileman
>>>
```

What do you think? I can try implementing the idea(s) if the green light is given.

**Comment by phil-s** [comment]
I concur.  I lost time to this issue a few days ago, when I was trying to downgrade `psysh` to test a problem, and I couldn't understand why I kept getting the wrong version despite composer seemingly making the change I'd asked for.  I'm not particularly knowledgeable about composer, so I just assumed *that* was my problem... it was by chance that I eventually discovered that the CWD was affecting which version I was actually getting (at which point there was some swearing involved).

**Comment by bobthecow** [comment]
For context, the reason it does this is because PsySH plays around in _your_ userland code.

So if you have a project that uses Symfony components or PHP Parser, you could (read: definitely will) get incompatible versions of those components autoloaded in seemingly non-deterministic ways, just because of which ones PsySH looks for before your application does. Then you have a mix of different files from different versions of what should be shared dependencies. It's a huge mess, and is even harder to sort out.

So if you have PsySH installed locally, calling a globally installed `psysh` binary will defer to that version, ensuring that you have the composer-resolved compatible dependency versions, and everything is happy....

I can totally see where that would be confusing, though.

I think it'd be fine letting people know when we're doing this. Technically it's not "using ./vendor/bin/psysh", though, it's using the locally installed source files autoloaded by Composer.

**Comment by phanan** [comment]
> I think it'd be fine letting people know when we're doing this. Technically it's not "using ./vendor/bin/psysh", though, it's using the locally installed source files autoloaded by Composer.

Sounds good to me. How should it clarify to users?

**Comment by bobthecow** [comment]
¯\_(ツ)_/¯ open to suggestions :)

**Comment by phanan** [comment]
Cool, I’ll try to come up with something as a PR.

**Comment by phanan** [comment]
So I have something up here https://github.com/phanan-forks/psysh/commit/30dd0cb480e825fbc38f0305edee470c42030c3c. The code works during development:

![image](https://user-images.githubusercontent.com/8056274/79041380-b1496980-7bef-11ea-93c6-ca2d67e1731d.png)

but weirdly enough [not after building](https://github.com/phanan-forks/psysh/commit/30dd0cb480e825fbc38f0305edee470c42030c3c#r38430134). As I'm not familiar with the building tool/process, @bobthecow do you think you can shed a light on this? Cheers!

**Comment by bobthecow** [comment]
How about this?

<img width="762" alt="Screen Shot 2020-05-02 at 11 30 53 AM" src="https://user-images.githubusercontent.com/53660/80872825-4aa4f200-8c69-11ea-974c-8bd8789c8236.png">

**Comment by phanan** [comment]
That looks great 👍

**Comment by kapitanluffy** [comment]
I just upgraded my version and saw the notice. I should probably close Issue #639 now.

I would recommend that we have an option to use the global version since the local versions tend to be older versions that does not have the features of the newer ones.

I am currently working on a Psysh plugin for an editor but because of this I cannot complete it because the older versions does not have a non-interactive mode. I could probably set it in a config file but for now I wanted it to work "out-of-the-box".
