### ISSUE TITLE
Use php-parallel-lint packages in 0.8.x

### ISSUE THREAD

**Issue by FrontEndCoffee** [bobthecow/psysh#635]
Since I cannot see that `0.8.x` is deprecated, it would be nice if these dependencies would be replaced with their suggested counterparts.

```
Package jakub-onderka/php-console-color is abandoned, you should avoid using it. Use php-parallel-lint/php-console-color instead.
Package jakub-onderka/php-console-highlighter is abandoned, you should avoid using it. Use php-parallel-lint/php-console-highlighter instead.
```

I'd be happy to set up a PR 😇

**Comment by GrahamCampbell** [comment]
👎 here. Either upgrade to 0.9.x, or just ignore the abandoned warnings. PHP 5.4 is also abandoned. I wonder if composer should print abandoned warnings for the PHP version too.

**Comment by bobthecow** [comment]
v0.8.x was released two years ago. There have been 18 releases since then. Some of 'em have been really really good. I would highly recommend updating at your earliest convenience.

Switching a dependency to a new package—by new maintainers—for such an old version of this library isn't a great idea. It increases risk for our users, and possibly introduces even more dependency and version hell as it interacts with other packages. 

If you need to keep using v0.8.x, feel free to ignore the deprecation warnings 🙂
