### ISSUE TITLE
Psysh using different version in vendor

### ISSUE THREAD

**Issue by kapitanluffy** [bobthecow/psysh#639]
Is there a way to prevent psysh from using the one in the vendors?

I am currently getting an outdated version even though I am trying to run my own psysh. I attached below screenshots for reference.

![image](https://user-images.githubusercontent.com/485799/83364379-8b606a00-a3d3-11ea-87e9-9846c9f5ab2f.png)

![image](https://user-images.githubusercontent.com/485799/83364383-9a471c80-a3d3-11ea-9535-290ff3b6b624.png)

My psysh version is 0.10.3 but when I run it on a folder with psysh installed in vendor, I get 0.9.12

**Comment by kapitanluffy** [comment]
As I mentioned in #626, I tried using the config file but the non-interactive mode is not available on older versions.

```
Fatal error: Uncaught Error: Undefined class constant 'INTERACTIVE_MODE_FORCED'
```

It would be totally awesome of you to have a `--global` option ❤️

**Comment by phil-s** [comment]
> Fatal error: Uncaught Error: Undefined class constant 'INTERACTIVE_MODE_FORCED'

You can instead just use:

    'interactiveMode' => 'forced',

instead of using the constant (which is defined with the value 'forced').  Strictly speaking using the constant is better; but the chances of that value *changing* are probably going to be slight, so that's a simple change to make.

Alternatively, you could test to see if the constant is `defined()`, and conditionally include that setting if it is.  The config file is just PHP, after all.

**Comment by kapitanluffy** [comment]
> > Fatal error: Uncaught Error: Undefined class constant 'INTERACTIVE_MODE_FORCED'
> 
> You can just use:
> 
> ```
> 'interactiveMode' => 'forced',
> ```
> 
> instead of using the constant (which is defined with the value 'forced'). Strictly speaking using the constant is better; but the chances of that value _changing_ are probably going to be slight, so that's a simple change to make.
> 
> Alternatively, you could test to see if the constant is `defined()`, and conditionally include that setting if it is. The config file is just PHP, after all.

Yes, I tried that but the local version was `0.9.x` which I assume has no non-interactive option since `forced` did not work.

**Comment by phil-s** [comment]
The only versions which would have trouble with a config file setting `'interactiveMode' => 'forced',` are 0.10.0 and 0.10.2 (there was no .1). 0.9.x will ignore the setting, but it doesn't need it -- it works that way by default.  Or at least, issue #621 only cropped up with the changes in 0.10.0.

**Comment by bobthecow** [comment]
PHP doesn't have good mechanisms for segregating code. Because it runs in userland, PsySH always defers to the version you have installed locally. Otherwise you get in situations where autoloaders can fight and you end up with a mix of local and global code in the same namespace.

We've added a notice when the local install takes priority, which hopefully makes this a bit more clear?
