### ISSUE TITLE
Different color for integers and doubles?

### ISSUE THREAD

**Issue by 1ma** [bobthecow/psysh#664]
A minor gripe I have with PsySH compared to Boris is that it uses the same purplish color to output both integer and double values.

![sample](https://i.imgur.com/GcRwpsD.png)

Sifting through the documentation I didn't see any option to customize these colors. If it's okay I'd like to try to contribute that change.

**Comment by bobthecow** [comment]
[VarDumper](https://symfony.com/doc/current/components/var_dumper.html), the library we use to present values, uses the decimal to distinguish between integers and doubles, rather than the color ([see the implementation here](https://github.com/symfony/var-dumper/blob/e1789346d5a42ce41635d5cca3fef96f02a5a6cf/Dumper/CliDumper.php#L140-L158)). Adding another themeable color would be a feature request for that library!

**Comment by 1ma** [comment]
Got it, thanks. If I can make it happen there I'll ping you again.
